development:
  adapter: mysql2
  database: celluloid_development
  user: root
  password:     
  host: 127.0.0.1
  port: 3306
  encoding: "utf8"
  connect_timeout: 2
  write_timeout: 2
  read_timeout: 2
          
test:
  adapter: mysql2
  database: celluloid_test
  user: root
  password: 
  host: 127.0.0.1
  port: 3306
  connect_timeout: 2
  write_timeout: 2
  read_timeout: 2


production:
  adapter: mysql2
  database: celluloid_production 
  user: root
  password: 
  host: 127.0.0.1
  port: 3306
  connect_timeout: 2
  write_timeout: 2
  read_timeout: 2

